#!/usr/bin/env python
# -*- coding: utf-8  -*-

""" rotor """

import sys
import getopt
import pygtk
pygtk.require('2.0')
import gtk
import subprocess
import math
import logging




def crcolor(color):
    """ convert hex color to cario color model """
    gtkcolor = gtk.gdk.Color(color)
    return (float(gtkcolor.red) / 65535,
            float(gtkcolor.green) / 65535,
            float(gtkcolor.blue) / 65535)


def usage():
    print "grotor [-v] [-s step] [-d display] [-t <title>] [-r host:port]"
    print "version 1.2"
    print "-v: turn on verbose debugging logging"
    print "-s: az button step, az degrees to step to create buttons (default=45)"
    print "-d: az display size, size in pixels of az graphic display (default=220)"
    print "-t: window title"
    print "-r: host and port (default 127.0.0.1:4533)"


class RotorApp(gtk.Window):
    """ Rotor """

    def __init__(self, azdisplay_title, rchostport,  azbutton_step=45, azdisplay_size=220):
        """ function """
        # main window
        logging.debug("rotor init")
        self.updatecount = 0
        self.azbutton_step = azbutton_step
        self.azdisplay_size = azdisplay_size
        self.azdisplay_title = azdisplay_title
        self.rotctl_path = "rotctl"
        self.rchostport = rchostport
        self.azimuth = 1.0

        # self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        super(RotorApp, self).__init__()

        #self.window.set_icon_from_file('grotor.png')
        self.connect("destroy", lambda w: gtk.main_quit())
        self.set_title(self.azdisplay_title)

        color = gtk.gdk.color_parse('#EEEEEE')
        self.modify_bg(gtk.STATE_NORMAL, color)

        # main box
        self.mainbox = gtk.VBox(False, 5)
        self.add(self.mainbox)

        # main box
        #     menubox
        #     posbox
        #     controlbox
        #     statusbox
        self.menubox = gtk.HBox(False, 0)
        self.posbox = gtk.VBox(False, 5)
        self.controlbox = gtk.HBox(False, 5)

        self.mainbox.pack_start(self.menubox, True, True, 5)
        self.mainbox.pack_start(self.posbox, False, False, 5)
        self.mainbox.pack_start(self.controlbox, True, True, 5)

        # main box
        #     menubox
        #     posbox
        #       eventbox1
        #           labelaz
        #       eventbox2
        #           labeltitle
        #     actionbox
        #           buttonstop
        #     controlbox
        #       azbox
        #           azbutboz1
        #           azbutboz2
        #     drawarea

        self.actionbox = gtk.VButtonBox()
        self.azbox = gtk.VBox(False, 5)
        self.azbutbox1 = gtk.HButtonBox()
        self.azbutbox2 = gtk.HButtonBox()

        self.controlbox.pack_start(self.actionbox, True, True, 5)
        self.controlbox.pack_start(self.azbox, True, True, 5)

        self.azbox.pack_start(self.azbutbox1, True, True, 0)
        self.azbox.pack_start(self.azbutbox2, True, True, 0)

        self.init_menu()
        self.init_aztext()
        self.init_azbuttons()
        self.init_ctlbuttons()
        self.init_azdisplay()
        self.init_statusbar()

        self.show_all()

        logging.debug("rotor init complete")

    def init_azbuttons(self):
        """ create the az buttons display"""
        self.azbuttonlist1 = []
        self.azbuttonlist2 = []

        for a in range(0, 179, self.azbutton_step):
            b = gtk.Button(str(a))
            self.azbuttonlist1.append(b)
        self.azbuttonlist1.append(gtk.Button(str(179)))

        for a in range(360, 181, -self.azbutton_step):
            b = gtk.Button(str(a))
            self.azbuttonlist2.append(b)
        self.azbuttonlist2.append(gtk.Button(str(181)))

        for b in self.azbuttonlist1:
            self.azbutbox1.add(b)
            b.connect("clicked", self.azbutcb, b.get_label())

        for b in self.azbuttonlist2:
            self.azbutbox2.add(b)
            b.connect("clicked", self.azbutcb, b.get_label())

    def init_ctlbuttons(self):
        """ create the control/action buttons display"""
        self.labelactionbox = gtk.Label("Move Az:")
        self.actionbox.add(self.labelactionbox)

        self.ccwbutton = gtk.Button("<<CCW")
        self.ccwbutton.connect("clicked", self.movebuttoncb, "CCW")
        self.actionbox.add(self.ccwbutton)

        self.stopbutton = gtk.Button("STOP")
        self.stopbutton.connect("clicked", self.stopbuttoncb, None)
        self.actionbox.add(self.stopbutton)

        self.cwbutton = gtk.Button("CW>>")
        self.cwbutton.connect("clicked", self.movebuttoncb, "CW")
        self.actionbox.add(self.cwbutton)

    def init_azdisplay(self):
        """ create the drawing area for az display """
        self.drawarea = gtk.DrawingArea()
        self.drawarea.set_size_request(self.azdisplay_size, self.azdisplay_size)
        self.mainbox.pack_start(self.drawarea, False, False, 0)
        self.drawarea.modify_bg(gtk.STATE_NORMAL, gtk.gdk.Color('#DDDDDD'))
        self.drawarea.connect('expose-event', self.expose)

    def init_statusbar(self):
        self.statusbar = gtk.Statusbar()
        self.mainbox.pack_start(self.statusbar, True, True, 0)
        self.statusbar.push(0, "initializing")

    def init_aztext(self):
        """ create the az text display"""
        self.eventbox1 = gtk.EventBox()
        color = gtk.gdk.color_parse('#FFFFFF')
        self.eventbox1.modify_bg(gtk.STATE_NORMAL, color)
        self.eventbox1.set_border_width(10)

        self.labelaz = gtk.Label()
        self.eventbox1.add(self.labelaz)
        self.posbox.pack_start(self.eventbox1, True, True, 0)

        self.eventbox2 = gtk.EventBox()
        color = gtk.gdk.color_parse('#EEEEEE')
        self.eventbox2.modify_bg(gtk.STATE_NORMAL, color)
        self.eventbox2.set_border_width(5)

        self.labeltitle = gtk.Label()
        self.eventbox2.add(self.labeltitle)
        self.posbox.pack_start(self.eventbox2, True, True, 0)

    def expose(self, drawarea, event, data=None):
        logging.debug("calling expose")
        self.drawable = self.drawarea.window
        self.cr = self.drawable.cairo_create()
        self.cr.set_source_rgb(*crcolor('#588C7E'))
        w = self.drawarea.allocation.width
        h = self.drawarea.allocation.height

        self.cr.translate(w / 2, h / 2)
        r = min(w / 2, h / 2) - 30

        self.cr.set_line_width(20)
        self.cr.arc(0, 0, r, 0, 2 * math.pi)
        self.cr.stroke_preserve()

        self.cr.set_source_rgb(*crcolor('#F9F6F4'))
        self.cr.fill()

        for i in xrange(12):
            self.cr.save()
            self.cr.set_line_width(3)
            self.cr.set_source_rgb(*crcolor('#0A0A0A'))
            if i % 3 == 0:
                inset = 0.2 * r
                outset = 0.2 * r
            else:
                inset = 0.1 * r
                outset = 0
            self.cr.move_to(0 + (r - inset) * math.cos(i * math.pi / 6),
                            0 + (r - inset) * math.sin(i * math.pi / 6))
            self.cr.line_to(0 + (r + outset) * math.cos(i * math.pi / 6),
                            0 + (r + outset) * math.sin(i * math.pi / 6))
            self.cr.stroke()
            self.cr.restore()

        self.cr.save()
        self.cr.set_line_width(6)
        self.cr.set_source_rgb(*crcolor('#990033'))
        self.cr.rotate(((self.azimuth + 270.0) * math.pi) / 180.0)
        self.cr.move_to(0, 0)
        self.cr.rel_line_to(r - (r * 0.1), 0)
        self.cr.stroke_preserve()
        self.cr.restore()

        return False

    def init_menu(self):
        self.menu = gtk.Menu()
        self.about = gtk.MenuItem("_About")
        self.menu.append(self.about)

        self.root_menu = gtk.MenuItem("Help")
        self.root_menu.set_submenu(self.menu)
        self.menubar = gtk.MenuBar()
        self.menubox.pack_start(self.menubar, False, False, 0)
        self.menubar.append(self.root_menu)


    def rc(self):
        """ function """
        logging.debug("calling rotctl get_pos")
        try:

            out_bytes = subprocess.check_output([self.rotctl_path, '-m', '2','-r',self.rchostport, 'p'],
                                                stderr=subprocess.STDOUT)
            out_text = out_bytes.decode('utf-8')
            output = out_text.splitlines()
            return output
        except subprocess.CalledProcessError as e:
            logging.error("rotctl get_pos called process error")
            self.updatestatus("failed to get position (rotctl issue?)")
            return ['-1', '0']

    def azbutcb(self, widget, data=None):
        """ function """
        self.callrotctlp(data)

    def callrotctlp(self, pos):
        logging.debug("calling rotctl set_pos")
        """ function """
        try:
            self.updatestatus("moving to %s degrees" % pos)
            out_bytes = subprocess.check_output([self.rotctl_path, '-m', '2', '-r',self.rchostport,'P', pos, '0'],
                                                stderr=subprocess.STDOUT)
            out_text = out_bytes.decode('utf-8')
            output = out_text.splitlines()
            return output
        except subprocess.CalledProcessError as e:
            logging.error("rotctl set_pos called process error")
            self.updatestatus("failed to set position (rotctl issue?)")
            return False

    def stopbuttoncb(self, widget, data=None):
        """ function """
        logging.debug("calling rotctl stop")
        self.updatestatus("stopping rotor")
        try:
            subprocess.check_output([self.rotctl_path, '-m', '2', '-r',self.rchostport,'S'],
                                    stderr=subprocess.STDOUT)
            return True
        except subprocess.CalledProcessError as e:
            self.updatestatus("failed to stop (rotctl issue?)")
            logging.error("rotctl stop called process error")
            return False

    def movebuttoncb(self, widget, data=None):
        """ function """
        logging.debug("calling rotctl move %s" % data)
        try:
            dir = "0"
            speed = "1"
            if data == "CW":
                dir = "16"
                speed = "100"
            elif data == "CCW":
                dir = "8"
                speed = "100"
            else:
                logging.error("rotctl move wrong data input")
                return False

            self.updatestatus("moving %s at speed  %s" % (dir, speed))
            subprocess.check_output([self.rotctl_path, '-m', '2', '-r',rchostport,'M', dir, speed],
                                    stderr=subprocess.STDOUT)
            return True
        except subprocess.CalledProcessError as e:
            logging.error("rotctl move called process error")
            self.updatestatus("failed to move rotor (rotctl issue?)")
            return False

    def position_update(self):
        """ function """
        logging.debug("calling rotor update")
        self.updatecount += 1
        if self.updatecount > 5:
            self.updatestatus("")
            self.updatecount = 0
        pos = self.rc()
        if float(pos[0]) < 0.0:
            logging.debug("get_pos failed")
        else:
            self.azimuth = float(pos[0])
        self.labelaz.set_markup(
            "<span font_family='FreeSans' weight='bold' font='28'>Azimuth: " +
            "%03.0f" % self.azimuth +
            "</span>")
        self.labeltitle.set_markup(
            "<span font_family='FreeSans' weight='regular' font='18'>" +
            "%s" % self.azdisplay_title +
            "</span>")
        self.drawarea.queue_draw()
        return True  # needed to keep the update method in the schedule

    def updatestatus(self, msg):
        self.statusbar.pop(0)
        self.statusbar.push(0, msg)



def main():
    """ function """
    gtk.main()


# start
if __name__ == "__main__":

    # parse command line options and args

    debug = logging.CRITICAL
    azbutton_step = 45
    azdisplay_size = 220
    azdisplay_title = "Rotor Control"
    rchostport = "127.0.0.1:4533"
    try:
        opts, args = getopt.getopt(sys.argv[1:], "vs:d:t:r:")
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for o, a in opts:
        if o == "-v":
            debug = logging.DEBUG
        elif o == "-s":
            azbutton_step = int(a)
        elif o == "-d":
            azdisplay_size = int(a)
        elif o == "-t":
            azdisplay_title = str(a)
        elif o == "-r":
            rchostport = str(a)

    #  setup logging

    logging.basicConfig(format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s', level=debug)
    logging.debug("starting logger")

    #  startup grotor
    rotor = RotorApp(azdisplay_title,rchostport,azbutton_step, azdisplay_size)
    gtk.timeout_add(1123, rotor.position_update)
    main()
